services:
  - type: web
    name: telegram-member-scraper
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATA_DIR
        value: /var/data
    disk:
      name: telegram-bot-data
      mountPath: /var/data
      sizeGB: 1
